# 06. 에러 핸들링

## assert

괄호 안을 평가해서 false이면 오류를 발생시키고 가스는 되돌려 주지 않는다. 테스트 용도, 불변성 체크 용도(?)로 사용한다고 함.

- **0.8.1부터 assert()가 에러를 발생 시키는 경우 panic()이라는 타입의 에러를 발생시킨다고 함. 또한 가스를 돌려받을 수 있게 변경됨**

```
function error() public pure{
    assert(false);
}
```

## revert

무조건 오류를 내고 가스는 환불해 준다. if문안에 쓰는 식으로 작동한다.

```
function error() public pure{
    if (조건) {
        revert("error"); // 에러 메시지를 괄호 안에 적을 수 있는데 동작이랑은 상관 없음.
    }

}
```

## require

괄호 안의 평가해서 false이면 오류를 발행시킨다. 두 번째 인자로 에러 메시지를 적을 수 있다. assert()와는 다르게 가스를 되돌려 준다.

```
function error() public pure{
    require(평가할 조건문, "에러 메시지!")
}
```

## try-catch

- **0.6.버젼부터 추가된 기능임**
